### ISSUE TITLE
给简历提个建议

### ISSUE THREAD

**Issue by pymongo** [unlimitbladeworks/amazing_idea#1]
粗略地看了一眼，给两处提个建议

## QQ邮箱

联系邮箱居然用QQ邮箱，会让面试官怀疑“这人是不会翻墙才用QQ邮箱吧”

注册个谷歌邮箱gmail不会吗？你把出生日期改到18岁以内，注册的时候不需要手机号码

---

## CSDN博客

本人谷歌搜索常年都是“-CSDN‘过滤掉CSDN，这个广告又多质量又差排版难看的网站只能骗骗小白吧？

有那么多博客解决方案，如wordpress等，都比CSDN好

综上两点，猜测你是面向百度+CSDN的开发者，建议你了解下面向Google+StackOverflow的搜索
尽量使用纯英文的谷歌搜索解决技术难题

**Comment by unlimitbladeworks** [comment]
好的，谢谢您的建议....刚学习的时候懒得自己搭建博客，所以初学那会儿直接依赖平台了，至于搜索问题，Google+StackOverflow的搜索，这两个也是我平时用的，技术方面，确实这两个很好，邮箱同理，Gmail移动端方面的时效性，是我所顾虑的，所以没有采用 gmail。。。
